### ISSUE TITLE
Error when line_size_vertical is set to 0

### ISSUE THREAD

**Issue by JulieBvs** [dputhier/scigenex#100]
plot_heatmap(res_gene[8,], cell_clusters = test_kmeans$cluster, line_size_vertical = 0)
 Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent

**Comment by dputhier** [comment]
This is ok.

**Comment by dputhier** [comment]
plot_heatmap(pbmc3k_medium_clusters[3,], cell_clusters = Idents(pbmc3k_medium), line_size_vertical = 0) 
|-- INFO :  Extracting cell identity. 
|-- INFO :  Centering matrix. 
|-- INFO :  Ceiling matrix. 
|-- INFO :  Flooring matrix. 
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
