### ISSUE TITLE
Add a parameter to plot_clust_enrichments to manage the number of character per line

### ISSUE THREAD

**Issue by JulieBvs** [dputhier/scigenex#123]

**Comment by dputhier** [comment]
I think you should have a look at the `label_wrap()`function from the scales library.

           library(scales)
           load_example_dataset("8028226/files/pbmc3k_medium_clusters_enr_sub")
           p <- plot_clust_enrichments(pbmc3k_medium_clusters_enr_sub)
           p +  scales::scale_y_discrete(labels = label_wrap(100))

**Comment by dputhier** [comment]
Tell me if it's ok.
