### ISSUE TITLE
Error when installing the package

### ISSUE THREAD

**Issue by JulieBvs** [dputhier/scigenex#124]
* checking for file ‘/tmp/Rtmpt2m0ZH/remotes76e31e8fa/dputhier-scigenex-66e6268/DESCRIPTION’ ... OK
cp: cannot stat 'dputhier-scigenex-66e6268/tests/testthat/.#test.cluster_set_to_xls.R': No such file or directory
 ERROR
copying to build directory failed
Error: Failed to install 'scigenex' from GitHub:
  System command 'R' failed, exit status: 1, stdout & stderr were printed

**Comment by dputhier** [comment]
fix in 19b437d3d6c7a8afee742e4978c39a0acbfe2f0c.
