### ISSUE TITLE
Control the level of verbosity

### ISSUE THREAD

**Issue by lionel-spinelli** [dputhier/scigenex#133]
Hello,

Would it be possible to add options in the "select_genes" and "gene_clustering" function (and perhaps others) to control the level of verbosity (and potentially remove all message apart main warnings and errors like usually done in R).
Current, the execution provide lot of INFO message that are not very usefull when compiling a R markdown report and that are "polluting" the report.

Thanks in advance
Best

**Comment by dputhier** [comment]
Did you tried this ?

       scigenex::set_verbosity(0)

**Comment by lionel-spinelli** [comment]
Hello,

I just tried and it work perfectly

Thanks you
Best

**Comment by lionel-spinelli** [comment]
Issue has been fixed by providing a global verbosity control
