### ISSUE TITLE
Error: pandoc document conversion failed with error 137

### ISSUE THREAD

**Issue by lionel-spinelli** [dputhier/scigenex#135]
Hello,

sometimes, I experienced an error when pandoc is trying to convert to HTML the module report. I am getting:

```
/usr/lib/rstudio-server/bin/quarto/bin/pandoc +RTS -K512m -RTS SciGeneX_interative_heatmap_filtered.knit.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output SciGeneX_interactive_heatmap_filtered.html --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --variable bs3=TRUE --section-divs --template /usr/local/lib/R/site-library/rmarkdown/rmd/h/default.html --highlight-style zenburn --variable theme=cerulean --mathjax --variable 'mathjax-url=https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --include-in-header /tmp/RtmpTUr3i7/rmarkdown-str14b656447414.html
Killed
Error: pandoc document conversion failed with error 137
```

After some research on internet, it appears this error may be linked to a too long conversion time or a memory issue during conversion. This can come from the sometime very large size of the heatmaps in the report. Indeed, I receive this error only on quite large datasets with a large amount of gene modules. 

A potential solution may be to change de -K512m option in Pandoc command to increase memory limit but I did not found how to do it from the Rmarkdown::render function used.

Thanks

**Comment by dputhier** [comment]
Hi Lionel,
Thanks for reporting the issue.  This function is definitely fragile. We
will try to find some time to dig into it.
Denis

Le lun. 13 nov. 2023 à 11:27, Lionel Spinelli ***@***.***> a
écrit :

**Comment by dputhier** [comment]
Maybe this would do the trick (see https://stackoverflow.com/questions/25599860/how-to-increase-stack-space-overflow-for-pandoc-in-r):

    ---
    title: "Habits"
    output:
      html_document:
        pandoc_args: [
          "+RTS", "-K64m",
          "-RTS"
        ]
    ---

Maybe a novel argument to the function could simply correct for this.
