### ISSUE TITLE
ClusterSet should implement a slot with the number of clusters.

### ISSUE THREAD

**Issue by dputhier** [dputhier/scigenex#14]
to avoid

         1:max(dbf_seurat@cluster) # see vignette. To be fixed.

**Comment by SebastienNin** [comment]
Done in [3161491](https://github.com/dputhier/scigenex/commit/3161491f8403d33a81758bf92e13e9cfaf8163da).

Need to add tests

**Comment by SebastienNin** [comment]
I forgot to create a new branch...

**Comment by SebastienNin** [comment]
I made the tests and tested them in commit [bca1469](https://github.com/dputhier/scigenex/commit/bca1469fe73dfc5df031ab429461177d63a255e6). 

They passed!
