### ISSUE TITLE
Need a method to extract gene list from clusters stored in a ClusterSet object

### ISSUE THREAD

**Issue by dputhier** [dputhier/scigenex#15]

**Comment by SebastienNin** [comment]
Done in commits [69cbe4a](https://github.com/dputhier/scigenex/commit/69cbe4a4dd18e3c1d4564a2fc444256036404f7a) + [7a03ed9](https://github.com/dputhier/scigenex/commit/7a03ed94984ae031be4150e3490a068dd513eed3)
