### ISSUE TITLE
DBFMCL filtering is unstable.

### ISSUE THREAD

**Issue by dputhier** [dputhier/scigenex#16]
Depending the same dataset may provide different results over time with same parameters.
This is highly problematic for reproducibility, to write tests, but also to create a documentation.
Would be cool if @fafa13 would help us to fix it !

        library(devtools)
        devtools::install_github("dputhier/scigenex")
        library(scigenex)
        m <- matrix(rnorm(80000), nc=20)
        m[1:100,1:10] <- m[1:100,1:10] + 4
        m[101:200,11:20] <- m[101:200,11:20] + 3
        m[201:300,5:15] <- m[201:300,5:15] + -2
        res <- DBFMCL(data=m,
                      distance_method="pearson",
                      av_dot_prod_min = 0,
                      inflation = 1.2,
                      k=25,
                      fdr = 10)
       nrow(res)

**Comment by JulieBvs** [comment]
Done since C code for DBF function have been replaced by R implementation of DBF using seed.
