### ISSUE TITLE
Failure (test.dbfmcl.R:12:3): Cheking DBFMCL is providing the right number of clusters

### ISSUE THREAD

**Issue by dputhier** [dputhier/scigenex#2]
When running make test on OSX the number of selected genes seem to differ from UNIX. @JulieBvs can you check the test is working on Linux.

       make test

        Testing dbfmcl
        ✔ |  OK F W S | Context
        ⠏ |   0       | test.dbfmcl                                                     The following parameters will be used :
            Working directory:  /Users/puthier/Documents/git/project_dev/dbfmcl/tests/testthat
            Name:  exprs
            Distance method:  pearson
            Number of neighbors:  25
            Number of randomizations:  3
            FDR:  10 %
            Perform clustering:  FALSE
            Visualize standard outputs from both mcl and cluster commands:  FALSE
            Memory used :  1024

        Randomization: 7994001 (1/1.000    ratio)
        Seed = 123
        Pre-computation for distances
        Computing distances: 100.00%
        Randomization: 7994001 obtained, 7994001 asked
        Computing FDR: 100.00%
        Computing cut-off
        number of conserved genes = 309
        Building graph
        Genes   core = 309   extra = 0
        DBF done
        ✖ |   1 1     | test.dbfmcl [1.2 s]
        ────────────────────────────────────────────────────────────────────────────────
        Failure (test.dbfmcl.R:12:3): Cheking DBFMCL is providing the right number of clusters
        res@size not equal to 298.
        1/1 mismatches
        [1] 309 - 298 == 11

**Comment by SebastienNin** [comment]
Tested on OSX 10.15.7. All test passed


|--  Done 
|--  creating file : /mnt/tests/testthat/test.mcl_out.txt 
|--  Reading and filtering MCL output: tmp_output/test.mcl_out.txt 
|--  3  clusters conserved after MCL partitioning. 
|--  0  clusters filtered out from MCL partitioning (size and mean dot product). 
|--  Cluster  1  -->  117  probes 
|--  Cluster  2  -->  110  probes 
|--  Cluster  3  -->  80  probes 
|--  Exporting results 
|--  --> Creating file :  tmp_output/ALL.sign.txt 
✓ |         1 | test.write_clust [62.2s]                                        

══ Results ═════════════════════════════════════════════════════════════════════
Duration: 308.9 s

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 14 ]

**Comment by SebastienNin** [comment]
I'm just realizing I tested on my docker on macos! @dputhier  can you try again on your mac?

**Comment by SebastienNin** [comment]
Closed because no answer
