### ISSUE TITLE
MCL implementation in R

### ISSUE THREAD

**Issue by dputhier** [dputhier/scigenex#3]
Currently DBFMCL use a call to MCL Unix command. There is a package for performing MCL analysis in R. Should be a good idea to go for it as it would make DBFMCL easier to install.
To be tested and implemented if performance and results are similar.
https://cran.r-project.org/web/packages/MCL/MCL.pdf

**Comment by dputhier** [comment]
One problem here is that the R implementation of MCL is slow compare to original (command line solution). We may propose both but the result may also differ...

**Comment by SebastienNin** [comment]
Hi again @dputhier 
I don't know if it come from the MCL implementation, but using the same input data as the tutorial (https://dputhier.github.io/dbfmcl/), I know got 19 gene clusters
![results_after_MCL_implementation](https://user-images.githubusercontent.com/18463343/126773260-3235423a-c4ee-472a-aec1-a6291759f1b3.png)
Before, I got 9 gene clusters
![results_before_MCL_implementation](https://user-images.githubusercontent.com/18463343/126773283-3cb965e5-d9a9-4870-8012-1772d6b86abe.png)

**Comment by dputhier** [comment]
Can you show the command line ?

**Comment by dputhier** [comment]
As explained in the installation section (https://dputhier.github.io/dbfmcl/) "we really encourage you to install the original MCL tool from S.M. van Dongen. Indeed, the R version is slower, not reproducible and produced very different results from the original version."

So the call to dbfmcl should contain a "mcl_cmd_line=TRUE". I may have also have perhaps changed the default value of k by mistake (not sure...).

**Comment by SebastienNin** [comment]
Ok I tried using "mcl_cmd_line=TRUE" and I got back my 9 gene clusters.
The behavior of mcl in R is very strange. I got 29 clusters when I tried it again.
Default k is 50, same as before.

**Comment by dputhier** [comment]
yep... I send an e-mail to the maintainer of MCL (R version) yesterday... It seems that it is no more maintained and has never reach a real level for being public...

**Comment by dputhier** [comment]
The maintainer proposed me to take in charge the developpement of this library but I not sure I will go for that...

**Comment by SebastienNin** [comment]
Well... I think we can stay with the MCL command line... I would take too much time to go into the code

**Comment by dputhier** [comment]
Yep, this is another project... A better solution would be to expose the C code of the original MCL version into a R library. But again this is a project in itself. I keep it in mind. 
In the meantime I think I will had a big red warning in the doc !
