### ISSUE TITLE
viz_enrich (error in evaluating the argument 'x' in selecting a method for function 'nrow': subscript out of bounds)

### ISSUE THREAD

**Issue by dputhier** [dputhier/scigenex#32]
> viz_enrich(dbf_seurat)
      Error in h(simpleError(msg, call)) : 
        error in evaluating the argument 'x' in selecting a method for function 'nrow': subscript out of bounds

**Comment by dputhier** [comment]
> is(dbf_seurat)
    [1] "ClusterSet"

        > dbf_seurat
                An object of class ClusterSet
                Name: 16aDYus0G1 
                Memory used:  19758104 
                Number of cells:  2638 
                Number of informative genes:  834 
                Number of clusters:  7 
                This object contains the following informations:
                     -  name 
                     -  data 
                     -  distances 
                     -  simulated_distances 
                     -  critical_distance 
                     -  cluster 
                     -  size 
                     -  top_genes 
                     -  center 
                     -  parameters 
                     -  algorithm 
                     -  cell_types 
                     -  cell_colors 
                     -  cell_order 
                     -  cluster_annotations 
                         *  distance_method  =  pearson 
                         *  k  =  50 
                         *  fdr  =  10 
                         *  seed  =  123 
                         *  inflation  =  8

**Comment by JulieBvs** [comment]
Could you please provide your code to reproduce this error ?
