### ISSUE TITLE
top_genes and clusters in plot_heatmap

### ISSUE THREAD

**Issue by dputhier** [dputhier/scigenex#38]
Got this error when using plot_heatmap

		> plot_heatmap(dbf, use_top_genes=TRUE, cluster = 1)
		|--  Centering matrix. 
		|--  Ordering cells based on hierarchical clustering. 
		|--  Ceiling matrix. 
		|--  Flooring matrix. 
		Error in m[genes_top, ] : subscript out of bounds
		> dbf@top_genes
		           gene.top.1      gene.top.2      gene.top.3      gene.top.4      gene.top.5     
		cluster.1  "H2-K1"         "Ccl21a"        "Fcgbp"         "Ifi27l2a"      "H2-D1"        
		cluster.2  "Gapdh"         "Stmn1"         "Ubb"           "Hmgn2"         "Pclaf"        
		cluster.3  "Gm48228"       "Mgat4c"        "Gucy2g"        "Abca17"        "5033417F24Rik"
		cluster.4  "1700024I08Rik" "Gm17200"       "Crocc2"        "Gm45418"       "Gm19689"      
		cluster.5  "Gm36356"       "1700029N11Rik" "Ttll6"         "Gmnc"          "Tsix"         
		cluster.6  "mt-Co1"        "mt-Atp6"       "Rps14"         "Rps28"         "Rpl37a"       
		cluster.7  "Gm553"         "Gm5784"        "5430431A17Rik" "Gabra2"        "Trav10n"      
		cluster.8  "Rpl30"         "Rpl22"         "Atp5mpl"       "Rpl23"         "Rpl34"        
		cluster.9  "Rmnd5a"        "Endou"         "Ccnd3"         "Satb1"         "Ets2"         
		cluster.10 "Rplp1"         "Rpsa"          "Actb"          "Rplp0"         "Laptm5"       
		cluster.11 "Rps21"         "Fau"           "Rps26"         "Chchd2"        "Rpl8"         
		cluster.12 "Tmod2"         "Cngb1"         "Gm43848"       "Gm29562"       "Tigd5"        
		cluster.13 "Rps17"         "Map1lc3b"      "Psma3"         "Gm10076"       "Uqcr10"       
		cluster.14 "G530011O06Rik" "1700041G16Rik" "Mkrn3"         "Cmklr1"        "Zfp456"       
		cluster.15 "mt-Co3"        "mt-Co2"        "Rps16"         "Rps20"         "Tpt1"         
		cluster.16 "Rps19"         "Rpl19"         "Rps6"          "Rpl12"         "Rps5"         
		cluster.17 "Gucy2e"        "Spink12"       "Serinc2"       "Gm16196"       "Gm13391"      
		cluster.18 "B2m"           "Pdia3"         "Tmsb4x"        "Npc2"          "Atp1b3"       
		cluster.19 "Boll"          "Fignl2"        "F8"            "Sntb1"         "Hoxa5"        
		cluster.20 "Sis"           "D630023F18Rik" "Mpo"           "Padi4"         "Arl4d"        
		cluster.21 "B930018H19Rik" "Loxl4"         "Gm38037"       "A430110L20Rik" "Pcdh1"        
		           gene.top.6 gene.top.7      gene.top.8 gene.top.9 gene.top.10    
		cluster.1  "H2-Ab1"   "H2-Eb1"        "H2-Aa"    "Mgp"      "Igfbp4"       
		cluster.2  "Snrpg"    "Slc25a5"       "Calm2"    "Rpl15"    "Cox7a2"       
		cluster.3  "Myo3b"    "Egf"           "Upk1a"    "Mamstr"   "Cldn3"        
		cluster.4  "Sypl2"    "9630002D21Rik" "Meig1"    "Gm16006"  "Dnah10"       
		cluster.5  "Lrfn2"    "Chst5"         "Adora2b"  "Adm2"     "Gjb6"         
		cluster.6  "Rps29"    "mt-Nd4"        "Rpl10a"   "Rps27"    "Rpl3"         
		cluster.7  "Dgkk"     "4632428C04Rik" "Cxxc4"    "Tmem136"  "Wee2"         
		cluster.8  "Rpl37"    "Rps7"          "Rps4x"    "Rps15a"   "Atp5j2"       
		cluster.9  "Themis"   "Myb"           "Aqp11"    "Rag2"     "Arl5c"        
		cluster.10 "Coro1a"   "Rps10"         "Rps9"     "Rplp2"    "Eef2"         
		cluster.11 "Arhgdia"  "Selplg"        "Mbnl1"    "Marcksl1" "Atp5g3"       
		cluster.12 "Wtip"     "Dennd5b"       "Caskin2"  "Zfp11"    "Vpreb1"       
		cluster.13 "Cct5"     "Uba1"          "Mapk1"    "Tpi1"     "Esd"          
		cluster.14 "Poll"     "Gpr137"        "Ogfod3"   "Ndufaf6"  "L2hgdh"       
		cluster.15 "mt-Nd1"   "Rpl27a"        "Rps15"    "mt-Nd3"   "mt-Nd2"       
		cluster.16 "Rps2"     "Rpl18a"        "Hsp90ab1" "Hspe1"    "Psmb8"        
		cluster.17 "Fam189a2" "Gm4890"        "Ticam2"   "Grk5"     "Pmaip1"       
		cluster.18 "Nfkbia"   "Sdf4"          "Tagln2"   "Rgs10"    "Lbh"          
		cluster.19 "Lrrc25"   "Plek2"         "Rom1"     "Anxa8"    "A730063M14Rik"
		cluster.20 "Taf4b"    "Lrg1"          "Fam110b"  "Sept10"   "Fitm2"        
		cluster.21 "Rassf6"   "Gpr160"        "Gm5134"   "Gm13546"  "Zdhhc23"

**Comment by JulieBvs** [comment]
Fixed in commit c760ede
