### ISSUE TITLE
storing av_dot_prod

### ISSUE THREAD

**Issue by dputhier** [dputhier/scigenex#39]
Hi,
I think it would be interesting to store the value of av_dot_prod in the DBFMCL object so that could re-run DBFMCL with and increased value of av_dot_prod_min to delete some contaminating clusters.
Best

**Comment by JulieBvs** [comment]
Done in commit c313ce5

Median values of dot product for each gene cluster are stored in dot_product slot of ClusterSet object (obj@dot_prodcut).
