### ISSUE TITLE
av_dot_prod_min

### ISSUE THREAD

**Issue by dputhier** [dputhier/scigenex#40]
When selecting clusters for dot product taking the average may be highly sensitive to outliers resulting in numerous spurious clusters. We should compute the median 

      if (mean(cur_dot_prod) > av_dot_prod_min & length(h) >
 
     ===> 

    if (median(cur_dot_prod) > av_dot_prod_min & length(h) >

This is examplified here with numerous signatures selected while they should be discarded.

 
<img width="518" alt="image" src="https://user-images.githubusercontent.com/1831198/168322632-9754b5c0-97d6-43ff-ae49-bce78ac993a4.png">

**Comment by JulieBvs** [comment]
Can you check if the problem is solved with your data?
