### ISSUE TITLE
Store cell order/cluster

### ISSUE THREAD

**Issue by dputhier** [dputhier/scigenex#45]
I dont know if there is any plan to store  cell order/cluster into the clusterSet object after plot_heatmap. This would be valuable so that the user may  manipulate the cell order/cluster later.
Best
Denis

**Comment by SebastienNin** [comment]
I can work on it,
It should be easy to implement

  library(scigenex)
  set.seed(123)
  m <- matrix(rnorm(40000), nc=20)
  m[1:100,1:10] <- m[1:100,1:10] + 4
  m[101:200,11:20] <- m[101:200,11:20] + 3
  m[201:300,5:15] <- m[201:300,5:15] + -2
  res <- DBFMCL(data=m,
          distance_method="pearson",
          av_dot_prod_min = 0,
          inflation = 2,
          k=25,
          fdr = 10)

htmp <-  plot_heatmap(res, ceil = 3, floor = -3)

colnames(htmp@plots[["Expression level"]]@data)
 [1] "sample4"  "sample2"  "sample1"  "sample3"  "sample9"  "sample5"  "sample7"  "sample8"  "sample6"  "sample10" "sample16" "sample18"
[13] "sample20" "sample17" "sample19" "sample11" "sample13" "sample14" "sample12" "sample15"

**Comment by JulieBvs** [comment]
Now, there is a function called cell_clust that run hierarchical clustering and cut the tree using cutreeHybrid from DynamicTreeCut R package. This function store the clustering result in cell_clusters slot of ClusterSet object.
