### ISSUE TITLE
plot_heatmap: Error in matrix(ncol = ncol(m)) : data is too long

### ISSUE THREAD

**Issue by dputhier** [dputhier/scigenex#56]
This is most probably due to the fact that hierarchical clustering is no more part of the function.

		> dbf_seurat <- top_genes(dbf, top = 10)
		|--  Results are stored in top_genes slot of ClusterSet object. 
		> plot_heatmap(dbf_seurat, use_top_genes = T)
		|--  Centering matrix. 
		|--  Ordering cells based on hierarchical clustering. 
		|--  Ceiling matrix. 
		|--  Flooring matrix. 
		Error in matrix(ncol = ncol(m)) : data is too long

It fails here when trying to access @cell_clusters$hclust_res$order which is NULL.

Best 

	    if (cell_ordering_method == "hclust") {
	      print_msg("Ordering cells based on hierarchical clustering.", 
	        msg_type = "DEBUG")
	      m <- m[, object@cell_clusters$hclust_res$order]
	      if (length(object@cell_clusters$labels) != 0) {
	        object@cell_clusters$labels <- object@cell_clusters$labels[colnames(m)]
	        object@cell_clusters$cores <- object@cell_clusters$cores[colnames(m)]
	      }
	    }

**Comment by JulieBvs** [comment]
I fixed that in the two commits above this message. It should work now.
