### ISSUE TITLE
1: In min(data, na.rm = TRUE) : 		  no non-missing arguments to min; returning Inf

### ISSUE THREAD

**Issue by dputhier** [dputhier/scigenex#72]
The example from find_gene_cluster is note working.

		set_verbosity(2)
		m <- create_4_rnd_clust()
		 
		res <- find_gene_clusters(data=m,
		                              distance_method="pearson",
		                              inflation = 2,
		                              k=75,
		                              row_sum=-Inf,
		                              highest=0.3,
		                              min_nb_supporting_cell = 0,
		                              fdr = 1e-8)
		res <- top_genes(res)

		plot_heatmap(res)
		|-- INFO :  Centering matrix. 
		|-- INFO :  Ceiling matrix. 
		|-- INFO :  Flooring matrix. 
		|-- INFO :  Plotting heatmap. 
		|-- DEBUG :  Adding labels. 
		|-- DEBUG :  Adding Titles. 
		Warning messages:
		1: In min(data, na.rm = TRUE) :
		  no non-missing arguments to min; returning Inf
		2: In max(data, na.rm = TRUE) :
		  no non-missing arguments to max; returning -Inf
		3: In min(z, na.rm = TRUE) :
		  no non-missing arguments to min; returning Inf
		4: In max(z, na.rm = TRUE) :
		  no non-missing arguments to max; returning -Inf
		5: In tickvals_helper(cb@zmin, cb@zmid, cb@zmax) : NaNs produced

**Comment by JulieBvs** [comment]
Fix in commit 5cec4a7
