### ISSUE TITLE
plot_heatmap: Error in i - 1 : non-numeric argument to binary operator

### ISSUE THREAD

**Issue by dputhier** [dputhier/scigenex#74]
Note: the combinations of arguments from plot_heatmap could be tested using data(pbmc_small) (from SeuratObject)

		library(SeuratObject)
		data(pbmc_small)
		library(scigenex)
		set_verbosity(3)

		res_pb <- find_gene_clusters(data=pbmc_small,
		                          distance_method="pearson",
		                          inflation = 2,
		                          k=80,
		                          row_sum=1,
		                          highest=0.75,
		                          min_nb_supporting_cell = 2,
		                          fdr = 0.05)

		plot_heatmap(res_pb, cell_clusters=Idents(pbmc_small))
		|-- INFO :  Ordering cells. 
		|-- INFO :  Centering matrix. 
		|-- INFO :  Ceiling matrix. 
		|-- INFO :  Flooring matrix. 
		Error in i - 1 : non-numeric argument to binary operator

**Comment by dputhier** [comment]
Note with this very artificial  dataset, it is also interesting to use ~all genes (without DBF filtering):

		res_pb <- find_gene_clusters(data=pbmc_small,
		                             distance_method="pearson",
		                             inflation = 2,
		                             k=50,
		                             row_sum=1,
		                             fdr = 0.05, no_dknn_filter = T)

                    plot_heatmap(res_pb, line_size_horizontal = 2)


Which produce 5 clusters.

**Comment by dputhier** [comment]
This one is still active but important.

**Comment by JulieBvs** [comment]
Fixed in commit
