### ISSUE TITLE
enrichGo Error in data.frame(..., check.names = FALSE) :  		  row names contain missing values

### ISSUE THREAD

**Issue by dputhier** [dputhier/scigenex#81]
Maybe the case when there is no enrichment was not taken into account.

		|-- INFO :  Enrichment analysis for cluster 19 
		|-- DEBUG :  Cluster 19
			|--Number of gene names converted to EntrezId : 23
			|--Number of gene names not converted to EntrezId : 0
			|-- Calling enrichGO. 
		|-- INFO :  Enrichment analysis for cluster 20 
		|-- DEBUG :  Cluster 20
			|--Number of gene names converted to EntrezId : 22
			|--Number of gene names not converted to EntrezId : 0
			|-- Calling enrichGO. 
		Error in data.frame(..., check.names = FALSE) : 
		  row names contain missing values

**Comment by dputhier** [comment]
Il seems this is an issue with clusterProfiler::enrichGO...

query_entrezid[,"ENTREZID"]
 [1] "26568"     "102638814" "170753"    "19366"     "16775"     "242050"    "226841"   
 [8] "624713"    "333182"    "20319"     "21959"     "653029"    "54353"     "69694"    
[15] "81877"     "234865"    "71998"     "16640"     "21976"     "27384"     "215210"   
[22] "101700"   


> go_name
[1] "org.Mm.eg.db"

ontology "all"

readable = TRUE

**Comment by dputhier** [comment]
The problem is encountered only when ontology = "ALL"...

**Comment by dputhier** [comment]
Moreover annotation 42 cluster is extremely slow...

**Comment by chifanbajizuideMrFan** [comment]
Yes I'm also experiencing this problem, when ont=ALL it reports an error, did you find the cause please?

**Comment by dputhier** [comment]
HI chifanbajizuideMrFan. Thank you for your feedback. We will try to find some time to dig into this. If I remember correctly this was an issue related to clusterProfiler::enrichGO. Do you have a minimum example on your side to try to reproduce ?
Best

**Comment by chensena** [comment]
I resolve this problem by restart the Rstudio.

**Comment by grimwoo** [comment]
> I resolve this problem by restart the Rstudio.

THIS IS THE REAL SOLUTION!
