### ISSUE TITLE
MCL package not available since last commit

### ISSUE THREAD

**Issue by SebastienNin** [dputhier/scigenex#9]
Hi @dputhier ,
I did a pull this morning before making a new branch and now I got this error when running reinstall.

> reinstall()
ℹ Loading dbfmcl
Error: Dependency package(s) 'MCL' not available.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
In (function (dep_name, dep_ver = "*")  :
  Dependency package 'MCL' not available.

**Comment by SebastienNin** [comment]
I post the issue too fast... I simply run install.packages("MCL")...
But It would be great if the installation is implemented in the package.

**Comment by dputhier** [comment]
I don't understand why it did not install automatically...

**Comment by dputhier** [comment]
I deinstall MCL and then try to reinstall it but it didn't worked (I installed it ~50 times yesterday...).
I got:

cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.10/data/experiment/bin/macosx/el-capitan/contrib/3.6/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.10/workflows/bin/macosx/el-capitan/contrib/3.6/PACKAGES.rds': HTTP status was '404 Not Found'trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/MCL_1.0.tgz'
Content type 'application/x-gzip' length 17630 bytes (17 KB)

This "Not Found'trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/MCL_1.0.tgz' indicates that MCL is no more available...

But strangely when using wget, it exists...

**Comment by dputhier** [comment]
Can you recheck... It is working for me now:

devtools::install_github("dputhier/dbfmcl")

**Comment by dputhier** [comment]
Indeed, can you delete both MCL and dbfmcl and re-test using:

devtools::install_github("dputhier/dbfmcl")

**Comment by SebastienNin** [comment]
It works!
No errors!
